### ISSUE TITLE
Push rejected, no Cedar-supported app detected

### ISSUE THREAD

**Issue by tnahvu** [simontaen/SpotifyTokenSwap#1]
Hi I'm following your instructions and have installed the gemfile but keep getting this error when trying to push to heroku.  I'm new to heroku.  

Last login: Tue Jan 27 23:05:20 on ttys000
Tuans-MacBook-Pro:~ TVU$ sudo gem install sinatra encrypted_strings
Password:
Successfully installed sinatra-1.4.5
Parsing documentation for sinatra-1.4.5
unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/sinatra/images/404.png, skipping
unable to convert "\x89" from ASCII-8BIT to UTF-8 for lib/sinatra/images/500.png, skipping
Successfully installed encrypted_strings-0.3.3
Parsing documentation for encrypted_strings-0.3.3
2 gems installed
Tuans-MacBook-Pro:~ TVU$ heroku login
Your version of git is 1.9.3. Which has serious security vulnerabilities.
More information here: https://blog.heroku.com/archives/2014/12/23/update_your_git_clients_on_windows_and_os_x
Enter your Heroku credentials.
Email: tnahvu@gmail.com
Password (typing will be hidden): 
Authentication successful.
updating...done. Updated to 3.24.5
Tuans-MacBook-Pro:~ TVU$ git clone https://github.com/tnahvu/SPOC1.0.git
Cloning into 'SPOC1.0'...
remote: Counting objects: 148, done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 148 (delta 60), reused 119 (delta 31)
Receiving objects: 100% (148/148), 4.06 MiB | 2.80 MiB/s, done.
Resolving deltas: 100% (60/60), done.
Checking connectivity... done.
Tuans-MacBook-Pro:~ TVU$ cd desktop/spoc1.0
Tuans-MacBook-Pro:spoc1.0 TVU$ heroku create --http-git
Your version of git is 1.9.3. Which has serious security vulnerabilities.
More information here: https://blog.heroku.com/archives/2014/12/23/update_your_git_clients_on_windows_and_os_x
Creating mysterious-earth-5905... done, stack is cedar-14
https://mysterious-earth-5905.herokuapp.com/ | https://git.heroku.com/mysterious-earth-5905.git
Git remote heroku added
Tuans-MacBook-Pro:spoc1.0 TVU$ git push heroku master
Counting objects: 148, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (140/140), done.
Writing objects: 100% (148/148), 4.06 MiB | 429.00 KiB/s, done.
Total 148 (delta 58), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: 
remote:  !     Push rejected, no Cedar-supported app detected
remote: 
remote: Verifying deploy....
remote: 
remote: !   Push rejected to mysterious-earth-5905.
remote: 
To https://git.heroku.com/mysterious-earth-5905.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/mysterious-earth-5905.git'

**Comment by simontaen** [comment]
Hi Tuan, you're checking out your own repository and not mine :)! Please follow the steps from my [Setup](https://github.com/simontaen/SpotifyTokenSwap#setup) and you'll get there.

**Comment by tnahvu** [comment]
Oops:) Works now.  Thanks!
